"""Initial migration

Revision ID: a926626a1869
Revises: 
Create Date: 2025-11-24 13:33:49.934181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a926626a1869'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('status_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_history_vin'), 'service_history', ['vin'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('regNo', sa.String(), nullable=True),
    sa.Column('chassis', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('vehicleManufacturerName', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('vehicleColour', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('normsType', sa.String(), nullable=True),
    sa.Column('bodyType', sa.String(), nullable=True),
    sa.Column('ownerCount', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('ownerFatherName', sa.String(), nullable=True),
    sa.Column('mobileNumber', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('statusAsOn', sa.DateTime(), nullable=True),
    sa.Column('regAuthority', sa.String(), nullable=True),
    sa.Column('regDate', sa.DateTime(), nullable=True),
    sa.Column('vehicleManufacturingMonthYear', sa.String(), nullable=True),
    sa.Column('rcExpiryDate', sa.DateTime(), nullable=True),
    sa.Column('vehicleTaxUpto', sa.String(), nullable=True),
    sa.Column('vehicleInsuranceCompanyName', sa.String(), nullable=True),
    sa.Column('vehicleInsuranceUpto', sa.DateTime(), nullable=True),
    sa.Column('vehicleInsurancePolicyNumber', sa.String(), nullable=True),
    sa.Column('rcFinancer', sa.String(), nullable=True),
    sa.Column('presentAddress', sa.Text(), nullable=True),
    sa.Column('permanentAddress', sa.Text(), nullable=True),
    sa.Column('vehicleCubicCapacity', sa.Numeric(), nullable=True),
    sa.Column('grossVehicleWeight', sa.Integer(), nullable=True),
    sa.Column('unladenWeight', sa.Integer(), nullable=True),
    sa.Column('vehicleCategory', sa.String(), nullable=True),
    sa.Column('rcStandardCap', sa.String(), nullable=True),
    sa.Column('vehicleCylindersNo', sa.Integer(), nullable=True),
    sa.Column('vehicleSeatCapacity', sa.Integer(), nullable=True),
    sa.Column('vehicleSleeperCapacity', sa.Integer(), nullable=True),
    sa.Column('vehicleStandingCapacity', sa.Integer(), nullable=True),
    sa.Column('wheelbase', sa.Integer(), nullable=True),
    sa.Column('vehicleNumber', sa.String(), nullable=True),
    sa.Column('puccNumber', sa.String(), nullable=True),
    sa.Column('puccUpto', sa.DateTime(), nullable=True),
    sa.Column('blacklistStatus', sa.Boolean(), nullable=True),
    sa.Column('blacklistDetails', sa.JSON(), nullable=True),
    sa.Column('permitIssueDate', sa.DateTime(), nullable=True),
    sa.Column('permitNumber', sa.String(), nullable=True),
    sa.Column('permitType', sa.String(), nullable=True),
    sa.Column('permitValidFrom', sa.DateTime(), nullable=True),
    sa.Column('permitValidUpto', sa.DateTime(), nullable=True),
    sa.Column('nonUseStatus', sa.String(), nullable=True),
    sa.Column('nonUseFrom', sa.String(), nullable=True),
    sa.Column('nonUseTo', sa.String(), nullable=True),
    sa.Column('nationalPermitNumber', sa.String(), nullable=True),
    sa.Column('nationalPermitUpto', sa.String(), nullable=True),
    sa.Column('nationalPermitIssuedBy', sa.String(), nullable=True),
    sa.Column('isCommercial', sa.Boolean(), nullable=True),
    sa.Column('nocDetails', sa.String(), nullable=True),
    sa.Column('financed', sa.Boolean(), nullable=True),
    sa.Column('class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_regNo'), 'vehicles', ['regNo'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('order_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=True),
    sa.Column('total_amount', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('invoices')
    op.drop_table('orders')
    op.drop_index(op.f('ix_vehicles_regNo'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_history_vin'), table_name='service_history')
    op.drop_table('service_history')
    # ### end Alembic commands ###
